### ISSUE TITLE
Monthly Statements from Chequings or Savings Accounts

### ISSUE THREAD

**Issue by benvanarragon** [mindcruzer/rbc-statement-to-csv#5]
I was wondering if it was possible to modify the code so it not only works for credit card statements but also monthly debit statements from your chequings or savings?

**Comment by nicolasluckie** [comment]
I believe @ElementalWarrior implemented this: [ElementalWarrior/rbc-statement-to-csv](https://github.com/ElementalWarrior/rbc-statement-to-csv)

**Comment by ElementalWarrior** [comment]
I put some effort into doing that. It did not perfectly iirc. But you could give it a shot

**Comment by dahchon** [comment]
@ElementalWarrior thanks! I tried it and found several issues:

1. If the user just opens the account in RBC, the first opening balance line would have no date:
<img width="671" alt="image" src="https://github.com/mindcruzer/rbc-statement-to-csv/assets/26046481/88320f5a-8c4c-4dea-a71d-ee46ff775bd3"> it would cause an error

2. Sometimes, the numbers are wrongly classified to Deposits or Withdrawls

It really sucks that the download all CSV functionality of RBC does not work well. It's pretty misleading
<img width="300" alt="image" src="https://github.com/mindcruzer/rbc-statement-to-csv/assets/26046481/36393386-5d4c-467a-89c6-36c9cdae868e">

**Comment by ElementalWarrior** [comment]
Yeah the chequing statements are much less uniform than the visa statements

**Comment by mindcruzer** [comment]
Such a simple thing to do on their end but here we are

**Comment by ycaty** [comment]
I made this for chequing statements, lmk how it works

https://github.com/ycaty/rbc-statement-to-csv

**Comment by rockiestar-com** [comment]
this is nice!

We made a chrome extension for this purpose as well.

https://8997228598163.gumroad.com/l/rbc-to-csv-chrome-ext-edge

will publish it to the edge/chrome store

**Comment by ycaty** [comment]
> this is nice!
> 
> We made a chrome extension for this purpose as well.
> 
> https://8997228598163.gumroad.com/l/rbc-to-csv-chrome-ext-edge
> 
> will publish it to the edge/chrome store

Looks interesting, do you have code for it?
