### ISSUE TITLE
External tool for visualizing expenses from CSV files

### ISSUE THREAD

**Issue by Mkranj** [mindcruzer/rbc-statement-to-csv#7]
Hi, found your GH from Coding with Lewis' video.
This is not really an issue, but your work is exactly what I wanted to see from my bank. I've been working on an expenses visualization dashboard which is live [here](https://spenddash.live/), with the github [here](https://github.com/Mkranj/spend-dash).  
The data format from RBC Statement To CSV is a perfect fit for this app, so maybe this could help you and your users. Just gotta change the Transaction Date column name to Date in the CSV. Cheers!

**Comment by mindcruzer** [comment]
Thanks I will check it out!
